version: '2'

services:
    php:
        build:
            context: docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - .:/var/www
            - "${SSH_PRIV_KEY}:/root/.ssh/id_rsa"

    nginx:
        build: docker/nginx
        ports:
            - "${BIND_IP}:${APP_PORT}:80"
            - "${BIND_IP}:${APP_PORT_SSL}:443"
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./var/log/nginx/:/var/log/nginx
        command: [nginx-debug, '-g', 'daemon off;']
