services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\Calculator\CalculatorInterface:
            tags: ['service.calculator']

    App\Calculator\Command\Calculate:
        arguments:
            $operations: !tagged_iterator service.calculator
